openapi: 3.0.3
info:
  title: API Dokumentasi IDEAT
  version: 1.0.0
  description: Dokumentasi untuk endpoint Aplikasi IDEAT
paths:
  /register:
    post:
      summary: Register pengguna baru
      description: Endpoint untuk mendaftarkan pengguna baru.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nama:
                  type: string
                email:
                  type: string
                jenisKelamin:
                  type: string
                tanggalLahir:
                  type: string
                  format: date
                beratBadan:
                  type: integer
                tinggiBadan:
                  type: integer
                password:
                  type: string
                confirmPassword:
                  type: string
              required:
                - nama
                - email
                - jenisKelamin
                - tanggalLahir
                - beratBadan
                - tinggiBadan
                - password
                - confirmPassword
      responses:
        "200":
          description: User berhasil didaftarkan.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User berhasil terdaftar
        "400":
          description: Validasi input gagal.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      nama:
                        type: array
                        items:
                          type: string
                        example:
                          - Nama tidak boleh kosong
                          - Nama hanya boleh berisi huruf dan spasi
                          - Nama harus minimal 3 karakter
                      email:
                        type: array
                        items:
                          type: string
                        example:
                          - Email sudah terdaftar
                          - Email tidak boleh kosong
                          - Email harus dalam format yang valid
                      jenisKelamin:
                        type: array
                        items:
                          type: string
                        example:
                          - Jenis kelamin tidak boleh kosong
                          - Jenis kelamin harus Laki-laki atau Perempuan
                      tanggalLahir:
                        type: array
                        items:
                          type: string
                        example:
                          - Tanggal lahir harus dalam format YYYY-MM-DD.
                      beratBadan:
                        type: array
                        items:
                          type: string
                        example:
                          - Berat badan tidak boleh kosong
                          - Berat badan harus berupa angka
                      tinggiBadan:
                        type: array
                        items:
                          type: string
                        example:
                          - Tinggi badan tidak boleh kosong
                          - Tinggi badan harus berupa angka
                      password:
                        type: array
                        items:
                          type: string
                        example:
                          - Password harus minimal 6 karakter
                          - Password tidak boleh kosong
                      confirmPassword:
                        type: array
                        items:
                          type: string
                        example:
                          - Konfirmasi password harus sama dengan password
      security: []
  /profile:
    get:
      summary: Mendapatkan data profil pengguna
      description: Endpoint untuk mendapatkan data profil pengguna yang diotentikasi.
      responses:
        "200":
          description: Data profil pengguna berhasil didapatkan.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      nama:
                        type: string
                        example: user
                      email:
                        type: string
                        example: user@example.com
                      jenisKelamin:
                        type: string
                        example: Laki-laki
                      tanggalLahir:
                        type: string
                        format: date-time
                        example: "2024-11-22"
                      beratBadan:
                        type: integer
                        example: 80
                      tinggiBadan:
                        type: integer
                        example: 178
        "400":
          description: Terjadi kesalahan validasi atau token tidak valid.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      token:
                        type: array
                        items:
                          type: string
                        example:
                          - Invalid token
                          - Authorization header missing
                          - Token has expired
                      id:
                        type: array
                        items:
                          type: string
                        example:
                          - User not found
      security:
        - Bearer_token: []
    put:
      summary: Update profil pengguna
      description: Endpoint untuk memperbarui profil pengguna.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nama:
                  type: string
                email:
                  type: string
                jenisKelamin:
                  type: string
                tanggalLahir:
                  type: string
                  format: date
                beratBadan:
                  type: integer
                tinggiBadan:
                  type: integer
              required:
                - nama
                - email
                - jenisKelamin
                - tanggalLahir
                - beratBadan
                - tinggiBadan
      responses:
        "200":
          description: Profil berhasil diperbarui.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Profil berhasil diperbarui
        "400":
          description: Validasi input gagal.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      nama:
                        type: array
                        items:
                          type: string
                        example:
                          - Nama tidak boleh kosong
                          - Nama hanya boleh berisi huruf dan spasi
                          - Nama harus minimal 3 karakter
                      email:
                        type: array
                        items:
                          type: string
                        example:
                          - Email tidak boleh kosong
                          - Email harus dalam format yang valid
                      jenisKelamin:
                        type: array
                        items:
                          type: string
                        example:
                          - Jenis kelamin tidak boleh kosong
                          - Jenis kelamin harus Laki-laki atau Perempuan
                      tanggalLahir:
                        type: array
                        items:
                          type: string
                        example:
                          - Tanggal lahir harus dalam format YYYY-MM-DD
                      beratBadan:
                        type: array
                        items:
                          type: string
                        example:
                          - Berat badan tidak boleh kosong
                          - Berat badan harus berupa angka
                      tinggiBadan:
                        type: array
                        items:
                          type: string
                        example:
                          - Tinggi badan tidak boleh kosong
                          - Tinggi badan harus berupa angka
      security:
        - Bearer_token: []
  /login:
    post:
      summary: login
      tags: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    x-stoplight:
                      id: jvhx69thhz51e
                    example: Login berhasil
                  data:
                    type: object
                    x-stoplight:
                      id: 7kgjg0sdd9by8
                    properties:
                      accessToken:
                        type: string
                        x-stoplight:
                          id: r064jvhad9pzh
                        example: xxxx
          headers:
            Set-Cookie:
              description: Header untuk menyimpan `refreshToken` di cookies.
              schema:
                type: string
                example: refreshToken=xxxx
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    x-stoplight:
                      id: zyxfxt697yfh2
                    properties:
                      email:
                        type: array
                        x-stoplight:
                          id: yxyj7j9uqpvsb
                        items:
                          x-stoplight:
                            id: d42grst47hylw
                          type: string
                          example:
                            - Email tidak boleh kosong
                            - Email harus dalam format yang valid
                      password:
                        type: array
                        x-stoplight:
                          id: lyuxddl76b372
                        items:
                          x-stoplight:
                            id: p3whjt1737hze
                          type: string
                          example:
                            - Password harus minimal 6 karakter
                            - Password tidak boleh kosong
      operationId: post-login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  x-stoplight:
                    id: ccvbjg5yl4sav
                "password ":
                  type: string
                  x-stoplight:
                    id: r2s06o2daxyh3
      parameters: []
      description: setelah login berhasil. untuk refreshToken disimpan di cookies
      security: []
  /token:
    get:
      summary: untuk refresh token
      tags: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    x-stoplight:
                      id: szeo6y859fyls
                    example: Access token generated successfully
                  data:
                    type: object
                    x-stoplight:
                      id: px437o1kiir98
                    properties:
                      accessToken:
                        type: string
                        x-stoplight:
                          id: wow87jvy4sdjd
                        example: xxxxxxx
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    x-stoplight:
                      id: 59zvix23u5u8w
                    properties:
                      token:
                        type: array
                        x-stoplight:
                          id: 8jeq1wznxwugx
                        items:
                          x-stoplight:
                            id: rr7znuc8yhoyx
                          type: string
                          example: Refresh token missing
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    x-stoplight:
                      id: z1ubs89x3qqfe
                    properties:
                      token:
                        type: array
                        x-stoplight:
                          id: 1j5kysceb46kx
                        items:
                          x-stoplight:
                            id: soc8006uy7ooh
                          type: string
                          example:
                            - Invalid refresh token
                            - Invalid or expired refresh token
      operationId: get-token
      parameters:
        - schema:
            type: string
          in: cookie
          name: refreshToken
          description: refresh token untuk meminta token baru ke backend
      security: []
  /password:
    put:
      summary: ubah password
      tags: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    x-stoplight:
                      id: e9fpwror43prw
                    example: Password berhasil diubah
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    x-stoplight:
                      id: srtj8ma2ckhkt
                    properties:
                      oldPassword:
                        type: array
                        x-stoplight:
                          id: 3nztcopkdbuju
                        items:
                          x-stoplight:
                            id: fqodwo6gp4hde
                          type: string
                          example:
                            - Password lama salah
                            - Password lama tidak boleh kosong
                      newPassword:
                        type: array
                        x-stoplight:
                          id: b808zr3mpzxli
                        items:
                          x-stoplight:
                            id: t0qoj3avujidq
                          type: string
                          example:
                            - Password baru harus minimal 6 karakter
                            - Password baru tidak boleh kosong
                      confirmNewPassword:
                        type: array
                        x-stoplight:
                          id: jtid2vk93yk6f
                        items:
                          x-stoplight:
                            id: 5wh59tix9ewz6
                          type: string
                          example:
                            - Konfirmasi password baru harus sama dengan password
                            - Konfirmasi password baru tidak boleh kosong
      operationId: put-password
      security:
        - Bearer_token: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                oldPassword:
                  type: string
                  x-stoplight:
                    id: h47q0oq3c4gsp
                newPassword:
                  type: string
                  x-stoplight:
                    id: 34jl5le6crqzi
                confirmNewPassord:
                  type: string
                  x-stoplight:
                    id: 9xsi4rw70iu28
x-internal: false
components:
  securitySchemes:
    Bearer_token:
      type: http
      scheme: bearer
security:
  - Bearer_token: []
