steps:
  # Step 1: Akses Secret dari Secret Manager dan simpan ke file .env
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "$(gcloud secrets versions access latest --secret=env-file)" > .env

  # Step 2: Build Docker image dan sertakan file .env
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/ideat-api"
      - "."

  # Step 3: Push Docker image ke Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/ideat-api"

  # Step 4: Deploy ke Cloud Run dengan file .env
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "ideat-api"
      - "--image=gcr.io/$PROJECT_ID/ideat-api"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--env-vars-file=.env"

substitutions:
  _PROJECT_ID: "divine-cortex-443408-j1"

timeout: "900s"
