steps:
  # Step 1: Akses Secret dari Secret Manager dan simpan ke file .env
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "$(gcloud secrets versions access latest --secret=env-file)" > .env

  # Step 2: Konversi file .env ke file env.yaml
  - name: "ubuntu"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "env_vars:" > env.yaml
        while IFS='=' read -r key value; do
          # Mengabaikan baris yang kosong atau komentar (#)
          if [[ ! -z "$key" && ! "$key" =~ ^# && ! -z "$value" ]]; then
            # Menambahkan key-value ke file YAML
            echo "  $key: \"$value\"" >> env.yaml
          fi
        done < .env

  # Step 3: Build Docker image dan sertakan file .env
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/ideat-api"
      - "."

  # Step 4: Push Docker image ke Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/ideat-api"

  # Step 5: Deploy ke Cloud Run dengan file env.yaml
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "ideat-api"
      - "--image=gcr.io/$PROJECT_ID/ideat-api"
      - "--region=asia-southeast2"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--env-vars-file=env.yaml"

substitutions:
  _PROJECT_ID: "divine-cortex-443408-j1"

timeout: "900s"

options:
  logging: CLOUD_LOGGING_ONLY
