steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ideat:$SHORT_SHA'
      - '.'

  # Deploy to Cloud Run with environment variables
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ideat'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ideat:$SHORT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - |
        PORT=${_PORT},
        NODE_ENV=${_NODE_ENV},
        DB_HOST=${_DB_HOST},
        DB_USER=${_DB_USER},
        DB_PASSWORD=${_DB_PASSWORD},
        DB_NAME=${_DB_NAME},
        ACCESS_TOKEN_SECRET=${_ACCESS_TOKEN_SECRET},
        MODEL_URL=${_MODEL_URL},
        BUCKET_NAME=${_BUCKET_NAME}

